apiVersion: v1
kind: Service
metadata:
  name: temperature-sensor
spec:
  selector:
    app: temperature-sensor
  ports:
    - port: 80
      targetPort: 8080
  #      nodePort: 30000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-sensor
  labels:
    app: temperature-sensor
spec:
  replicas: 1
  template:
    metadata:
      name: temperature-sensor
      labels:
        app: temperature-sensor
    spec:
      containers:
        - name: temperature-sensor
          image: temperature-sensor
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: temperature-sensor
