apiVersion: v1
kind: Service
metadata:
  name: sensormanager
spec:
  selector:
    app: sensormanager
  ports:
    - port: 8081
      targetPort: 8081
  #      nodePort: 30000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensormanager
  labels:
    app: sensormanager
spec:
  replicas: 1
  template:
    metadata:
      name: sensormanager
      labels:
        app: sensormanager
    spec:
      containers:
        - name: sensormanager
          image: sensormanager
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
      restartPolicy: Always
  selector:
    matchLabels:
      app: sensormanager
