server:
    port: 8082
spring:
    application:
        name: temperature-sensor
    datasource:
        password: password
#        url: jdbc:postgresql://localhost:5432/sensormanager
        url: jdbc:postgresql://sensordb-postgresql.default.svc.cluster.local:5432/sensormanager
        username: amigoscode
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false
    kafka:
        bootstrap-servers: poecilia:9092
sensormanager:
    topic:
        temperature: temperature
        temperaturechange: temperaturechange
