spring:
    datasource:
        password: password
        url: jdbc:postgresql://sensordb-postgresql.default.svc.cluster.local:5432/sensormanager
        username: amigoscode
    kafka:
        bootstrap-servers: my-release-kafka.default.svc.cluster.local
