spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://sensordb-postgresql.default.svc.cluster.local:5432/sensormanager
        username: postgres
    kafka:
        bootstrap-servers: sensorkafka.default.svc.cluster.local:9092
